kind: Service
apiVersion: v1
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort:  5432
  type: ClusterIP
  clusterIP: None

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgvolumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp2

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9.5-alpine
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data/pgdata"
              name: pgdata
              subPath: pgdata
          env:
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cc-secrets
                  key: databaseUsername
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cc-secrets
                  key: databasePassword
          resources:
            requests:
              cpu: 300m
              memory: 300Mi
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgvolumeclaim
