---
- name: "Change database.password to database.encryptedPassword in deployerConfigContext.xml"
  xml:
    file: "{{ install_home }}/apps/cas/WEB-INF/deployerConfigContext.xml"
    xpath: //*[name()='bean' and @id='dataSource']
    namespaces:
      p: http://www.springframework.org/schema/p
    attribute: p:encryptedPassword
    value: "${database.encryptedPassword}"
