---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik
        name: traefik-ingress-lb
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - name: http
          containerPort: 80
        # 8080 is the traefik dashboard port
        - containerPort: 8080
        args:
        - --web
        - --kubernetes

---

kind: Service
apiVersion: v1
metadata:
  name: traefik
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
  clusterIP: None
  

---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-daemon
  namespace: kube-system
  labels:
    app: nginx-daemon
spec:
  template:
    metadata:
      labels:
        app: nginx-daemon
    spec:
      containers:
      - name: nginx-daemon
        image: quay.io/aptible/nginx
        env:
        - name: UPSTREAM_SERVERS
          value: 'traefik.kube-system.svc.cluster.local'
        - name: FORCE_SSL
          value: 'true'
        ports:
        - name: https
          containerPort: 443
          hostPort: 443
        - name: http
          containerPort: 80
          hostPort: 80
      restartPolicy: Always
---

kind: Service
apiVersion: v1
metadata:
  name: traefik-dashboard
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
