---
- name: Create necessary administrator folders
  file:
    path: "{{ install_home }}/{{ item }}"
    state: directory
    recurse: true
    mode: 0755
  with_items:
    - "apps"
    - "apps/mgmtConsole"
    - "certificates"
    - "configuration"
- name: "Copy tools artifacts"
  copy:
    src: "{{ artifacts_path }}/tools/{{ item }}"
    dest: "{{ install_home }}/tools/"
  with_items:
    - "common"
    - "crypt"
- name: Copy apps
  copy:
    src: "{{ artifacts_path }}/apps/{{ item }}"
    dest: "{{ install_home }}/apps/"
  with_items:
    - "dcsf.war"
- name: Unpack app (war file) to apps folder
  unarchive:
    remote_src: true
    src: "{{ artifacts_path }}/apps/mgmtConsole.war"
    dest: "{{ install_home }}/apps/mgmtConsole"
    mode: 0644
- name: Create server-template.xml
  template:
    src: server-template.xml.j2
    dest: "{{ install_home }}/configuration/server-template.xml"
- name: Create entrypoint for container
  template:
    src: entrypoint.j2
    dest: "{{ docker_entrypoint_home }}/entrypoint"
    mode: "0755"
- include: configure_mgmt_web_xml.yml
