---
- hosts: 127.0.0.1
  remote_user: root
  vars:
    artifacts_path: "/destiny_artifacts"
  roles:
    - role: tomcat-common
      tomcat_lib_jars:
        - shared/lib/crypt.jar
        - shared/lib/server-security.jar
      tomcat_shared_jars:
        - shared/xlib/commons-logging-1.1.1.jar
        - shared/lib/common-version.jar
        - shared/lib/server-base.jar
      tomcat_endorsed_jars:
        - shared/xlib/bcprov-jdk15on-151.jar
    - role: dpc
